# Generated by Django 2.2.5 on 2019-10-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=25)),
                ('address_street_secondary', models.CharField(blank=True, max_length=25)),
                ('address_apt', models.CharField(blank=True, max_length=10)),
                ('address_city', models.CharField(max_length=15)),
                ('address_state', models.CharField(max_length=15)),
                ('address_zip', models.IntegerField()),
                ('address_country', models.CharField(max_length=25)),
                ('address_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('book_title', models.CharField(max_length=100)),
                ('book_description', models.CharField(blank=True, max_length=1000)),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('file_path', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('primary_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('nickname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('email_secondary', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('start_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('primary_list', models.BooleanField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer', verbose_name='user list assosiated to')),
            ],
        ),
        migrations.CreateModel(
            name='Wrote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('Book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Author')),
            ],
        ),
        migrations.CreateModel(
            name='WishListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book', verbose_name='book in list')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.WishList', verbose_name='wish list associated with this item')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer', verbose_name='user list is assosiated to')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book', verbose_name='book in cart')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer', verbose_name='user cart assosiated to')),
            ],
        ),
        migrations.CreateModel(
            name='SavedForLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book', verbose_name='book in list')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer', verbose_name='user item is assosiated to')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('sale_total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('card_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.CreditCards')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Addresses')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Sales')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
            ],
        ),
        migrations.AddField(
            model_name='creditcards',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer', verbose_name='customer card is related to'),
        ),
        migrations.CreateModel(
            name='Comments_Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book', verbose_name='book comment/rating is for')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Genre', verbose_name='book genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Publisher', verbose_name='publisher'),
        ),
        migrations.AddField(
            model_name='addresses',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer', verbose_name='user address is associated to'),
        ),
    ]
