# Generated by Django 2.2.5 on 2019-10-14 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitems',
            name='username',
        ),
        migrations.AlterField(
            model_name='comments_ratings',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Customer', verbose_name='customer doing the rating/commenting'),
        ),
    ]
