# Generated by Django 2.2.5 on 2019-10-17 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20191013_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file_path',
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='sales_rank',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
