# Generated by Django 2.2.5 on 2019-10-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20191017_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='comments_ratings',
            name='comment',
            field=models.CharField(max_length=2000),
        ),
    ]
