# Generated by Django 2.2.5 on 2019-10-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20191017_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='comments_ratings',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
