# Generated by Django 2.2.6 on 2019-10-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20191017_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_zip',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='sales_rank',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='comments_ratings',
            name='rating',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='creditcards',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
