# Generated by Django 2.2.6 on 2019-10-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20191017_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='sales_rank',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='comments_ratings',
            name='rating',
            field=models.CharField(max_length=3),
        ),
    ]
