# Generated by Django 2.2.6 on 2019-10-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20191017_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='sales_rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comments_ratings',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='creditcards',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
