# Generated by Django 2.2.6 on 2019-10-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_auto_20191017_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='address_apt',
            new_name='apt',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='address_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='address_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='address_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='address_street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='address_street_secondary',
            new_name='street_secondary',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='address_zip',
            new_name='zip_code',
        ),
    ]
