# Generated by Django 2.2.6 on 2019-10-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_auto_20191017_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments_Ratings',
            new_name='CommentsRatings',
        ),
    ]
