# Generated by Django 2.2.5 on 2019-10-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_auto_20191017_2329'),
        ('bookstore', '0005_auto_20191018_0005'),
    ]

    operations = [
    ]
