# Generated by Django 2.2.6 on 2019-10-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_merge_20191018_2147'),
        ('bookstore', '0014_merge_20191018_1401'),
    ]

    operations = [
    ]
