# Generated by Django 2.2.6 on 2019-10-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_merge_20191018_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wrote',
            old_name='book_id',
            new_name='book',
        ),
    ]
