# Generated by Django 2.2.6 on 2019-10-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_auto_20191019_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='commentrating',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale_id',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='savedforlater',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='wrote',
            old_name='author_id',
            new_name='author',
        ),
    ]
