# Generated by Django 2.2.5 on 2019-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0018_auto_20191108_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.BigIntegerField(),
        ),
    ]
