# Generated by Django 2.2.5 on 2019-11-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0019_auto_20191109_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
