# Generated by Django 2.2.5 on 2019-11-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_auto_20191109_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.CharField(max_length=2000),
        ),
    ]
